import { StyleSheet } from "react-native";

export const stylesWeb = StyleSheet.create({
  ProfileLayout: {
    height: "100vh",
    backgroundColor: "silver",
    padding: "80px",
    columnCount: "2",
    columnWidth: "50%",
    display: "flex",
    flexDirection: "row",
    paddingTop: 70,
  },
  layout: {
    minHeight: "100vh",
    backgroundColor: "silver",
    padding: "40px",
    paddingTop: 70,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
  },
  content: {
    maxWidth: 900,
  },
  contactContent: {
    width: 600,
    borderRadius: 8,
    boxShadow: "6px 10px 11px 2px dimgray, -1px -1px 11px dimgray",
    padding: 30,
  },
  profilePic: {
    height: 450,
    width: 450,
    alignSelf: "center",
    boxShadow: "4px 4px 12px black",
  },
  heading: {
    fontSize: 50,
    fontWeight: "bold",
    color: "#082c45",
    paddingBottom: 20,
    textShadow: "4px 12px 11px rgb(85, 84, 84)",
  },
  CareerHeading: {
    fontSize: 50,
    fontWeight: "bold",
    color: "#082c45",
    paddingBottom: 20,
    textShadow: "4px 12px 11px rgb(85, 84, 84)",
  },
  body: {
    fontSize: 22,
    color: "#082c45d7",
    paddingBottom: 18,
  },
  column: {
    flex: "40%",
  },
  subheading: {
    fontSize: 30,
    fontWeight: "bold",
    color: "#082c45d7",
    paddingRight: 5,
  },
  subheadingCareer: {
    fontSize: 30,
    fontWeight: "bold",
    color: "#082c45d7",
    paddingBottom: 8,
  },
  input: {
    width: 400,
    backgroundColor: "white",
    height: 26,
    borderRadius: 5,
    marginBottom: 10,
    marginTop: 4,
  },
  submit: {
    width: 80,
    backgroundColor: "#082c45",
    margin: 20,
    padding: 10,
    borderRadius: 4,
    boxShadow: "4px 8px 11px dimgray",
  },
  submitText: {
    color: "white",
    margin: "auto",
  },
  center: {
    margin: "auto",
  },
  Header: {
    flex: 1,
    flexDirection: "row",
    justifyContent: "space-around",
    alignItems: "center",
    backgroundColor: "#082c45",
    width: "100vw",
    color: "white",
    padding: 10,
  },
  HeaderTitle: {
    fontSize: 25,
    color: "white",
  },
  HeaderBar: {
    flexDirection: "row",
    backgroundColor: "#082c45",
    width: "100%",
    padding: 5,
    justifyContent: "space-around",
    marginBottom: 0,
  },
  headerText: {
    color: "white",
    fontWeight: "bold",
    alignItems: "center",
    fontSize: 18,
    padding: 8,
  },
});

export const stylesMobile = StyleSheet.create({
  ProfileLayout: {
    minHeight: "100vh",
    backgroundColor: "silver",
    padding: "40px",
    paddingTop: 30,
  },
  layout: {
    minHeight: "100vh",
    backgroundColor: "silver",
    padding: 15,
    paddingTop: 30,
  },
  profilePic: {
    height: 300,
    width: 300,
    alignSelf: "center",
    boxShadow: "4px 4px 12px black",
    marginBottom: 20,
  },
  heading: {
    fontSize: 50,
    fontWeight: "bold",
    color: "#082c45",
    paddingBottom: 20,
  },
  CareerHeading: {
    fontSize: 44,
    fontWeight: "bold",
    color: "#082c45",
    paddingBottom: 20,
  },
  body: {
    fontSize: 22,
    color: "#082c45d7",
    paddingBottom: 10,
  },
  subheading: {
    fontSize: 30,
    fontWeight: "bold",
    paddingBottom: 8,
  },
  subheadingCareer: {
    fontSize: 30,
    fontWeight: "bold",
    color: "#082c45d7",
    paddingBottom: 5,
  },
  contactContent: {
    borderRadius: 8,
    boxShadow: "4px 6px 11px 2px dimgray",
    padding: 30,
  },
  input: {
    width: 200,
    backgroundColor: "white",
    height: 26,
    borderRadius: 5,
    marginBottom: 10,
    marginTop: 4,
  },
  submit: {
    width: 80,
    backgroundColor: "#082c45",
    margin: 20,
    padding: 10,
    borderRadius: 4,
    boxShadow: "4px 8px 11px dimgray",
  },
  submitText: {
    color: "white",
    margin: "auto",
  },
  center: {
    margin: "auto",
  },
  Header: {
    flex: 1,
    flexDirection: "column",
    justifyContent: "space-around",
    alignItems: "center",
    backgroundColor: "#082c45",
    width: "100vw",
    color: "white",
    padding: 10,
    paddingTop: 20,
  },
  HeaderTitle: {
    fontSize: 25,
    color: "white",
  },
  HeaderBar: {
    flexDirection: "row",
    backgroundColor: "#082c45",
    width: "100%",
    padding: 5,
    justifyContent: "space-around",
    marginBottom: 0,
  },
  headerText: {
    color: "white",
    fontWeight: "bold",
    alignItems: "center",
    fontSize: 12,
    padding: 8,
  },
});
