import { StyleSheet } from "react-native";

export const stylesWeb = StyleSheet.create({
  ProfileLayout: {
    height: 500,
    backgroundColor: "#082c45",
    padding: 80,
    display: "flex",
    flexDirection: "row",
    paddingTop: 70,
  },
  layout: {
    minHeight: "100%",
    backgroundColor: "#082c45",
    padding: 40,
    paddingTop: 70,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
  },
  content: {
    maxWidth: 900,
  },
  contactContent: {
    width: 600,
    borderRadius: 8,
    padding: 30,
  },
  profilePic: {
    height: 450,
    width: 450,
    alignSelf: "center",
    borderRadius: 8,
  },
  heading: {
    fontSize: 50,
    fontWeight: "bold",
    color: "white",
    paddingBottom: 20,
  },
  headingPortfolio: {
    fontSize: 50,
    fontWeight: "bold",
    color: "white",
    paddingBottom: 20,
  },
  CareerHeading: {
    fontSize: 50,
    fontWeight: "bold",
    color: "white",
    paddingBottom: 20,
  },
  body: {
    fontSize: 22,
    color: "white",
    paddingBottom: 18,
  },
  column: {
    width: "50%",
  },
  subheading: {
    fontSize: 30,
    fontWeight: "bold",
    color: "white",
    paddingRight: 5,
  },
  subheadingCareer: {
    fontSize: 30,
    fontWeight: "bold",
    color: "white",
    paddingBottom: 8,
  },
  input: {
    width: 400,
    backgroundColor: "white",
    height: 26,
    borderRadius: 5,
    marginBottom: 10,
    marginTop: 4,
  },
  submit: {
    width: 80,
    backgroundColor: "white",
    margin: 20,
    padding: 10,
    borderRadius: 4,
  },
  submitText: {
    color: "#082c45",
    margin: "auto",
  },
  center: {
    margin: "auto",
  },
  Header: {
    flex: 1,
    flexDirection: "row",
    justifyContent: "space-around",
    alignItems: "center",
    backgroundColor: "#082c45",
    width: "100%",
    color: "white",
    padding: 10,
    maxHeight: "100%",
  },
  HeaderTitle: {
    fontSize: 25,
    color: "white",
  },
  HeaderBar: {
    flexDirection: "row",
    backgroundColor: "#082c45",
    width: "100%",
    padding: 5,
    justifyContent: "space-around",
    marginBottom: 0,
  },
  headerText: {
    color: "white",
    fontWeight: "bold",
    alignItems: "center",
    fontSize: 18,
    padding: 8,
  },
  container: {
    flex: 1,
    justifyContent: "space-between",
  },
  scrollView: {
    borderTopWidth: 2,
    borderColor: "#082c45",
    height: 400,
  },
  navbar: {
    height: 70,
    top: 0,
  },
  scrollContentContainer: {
    justifyContent: "space-between",
  },
  main: {
    flex: 1,
    backgroundColor: "#082c45",
  },
  entry: {
    width: "94%",
    padding: 20,
    borderColor: "#082c45",
    borderWidth: 1,
    borderRadius: 8,
    alignItems: "center",
    marginBottom: 20,
    marginTop: 20,
    marginBottom: 30,
  },
  video: {
    height: 320,
    width: 440,
    borderRadius: 12,
    marginBottom: 14,
  },
  entryLink: {
    color: "#082c45",
    display: "flex",
    justifyContent: "center",
    backgroundColor: "white",
    padding: 5,
    borderRadius: 20,
    width: 60,
    marginRight: 30,
  },
  linkContainer: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    alignContent: "space-between",
    marginTop: 10,
  },
  entryText: {
    color: "#082c45",
    textAlign: "center",
    fontSize: 20,
  },
  portfolioColumn: {
    alignItems: "center",
  },
});

export const stylesMobile = StyleSheet.create({
  ProfileLayout: {
    
    backgroundColor: "#082c45",
    padding: 40,
    paddingTop: 30,
  },
  layout: {
   
    backgroundColor: "#082c45",
    padding: 25,
    paddingTop: 30,
  },
  profilePic: {
    height: 300,
    width: 300,
    alignSelf: "center",
    marginBottom: 20,
  },
  heading: {
    fontSize: 35,
    fontWeight: "bold",
    color: "white",
    paddingBottom: 20,
  },
  headingPortfolio: {
    fontSize: 35,
    fontWeight: "bold",
    color: "white",
    paddingBottom: 20,
    alignSelf: "center",
  },
  CareerHeading: {
    fontSize: 40,
    fontWeight: "bold",
    color: "white",
    paddingBottom: 20,
  },
  body: {
    fontSize: 22,
    color: "white",
    paddingBottom: 10,
  },
  subheading: {
    fontSize: 30,
    fontWeight: "bold",
    paddingBottom: 8,
    color: "white",
  },
  subheadingCareer: {
    fontSize: 30,
    fontWeight: "bold",
    color: "white",
    paddingBottom: 5,
  },
  contactContent: {
    borderRadius: 8,

    padding: 30,
  },
  input: {
    width: "100%",
    backgroundColor: "white",
    height: 26,
    borderRadius: 5,
    marginBottom: 10,
    marginTop: 4,
  },
  submit: {
    width: 80,
    backgroundColor: "white",
    margin: 20,
    padding: 10,
    borderRadius: 4,
    alignItems: "center",
  },
  submitText: {
    color: "#082c45",
    margin: "auto",
  },
  center: {
    margin: "auto",
    justifyContent: "center",
  },
  Header: {
    flex: 1,
    flexDirection: "column",
    justifyContent: "space-around",
    alignItems: "center",
    backgroundColor: "#082c45",
    width: "100%",
    color: "white",
    padding: 10,
    paddingTop: 20,
  },
  HeaderTitle: {
    fontSize: 25,
    color: "white",
  },
  HeaderBar: {
    flexDirection: "row",
    backgroundColor: "#082c45",
    width: "100%",
    padding: 1,
    justifyContent: "space-around",
    marginBottom: 0,
  },
  headerText: {
    color: "white",
    fontWeight: "bold",
    alignItems: "center",
    fontSize: 12,
    padding: 4,
  },
  container: {
    flex: 1,
    justifyContent: "space-between",
  },
  scrollView: {
    borderTopWidth: 2,
    borderColor: "#082c45",
    height: "70%",
  },
  navbar: {
    height: "15%",
    top: 0,
  },
  scrollContentContainer: {
    justifyContent: "space-between",
  },
  main: {
    flex: 1,
    backgroundColor: "#082c45",
  },
  entry: {
    width: "94%",
    padding: 10,
    borderColor: "#082c45",
    borderWidth: 2,
    borderRadius: 8,
    alignItems: "center",
    marginTop: 20,
    marginBottom: 30,
  },
  video: {
    height: 220,
    width: 240,
    borderRadius: 12,
    marginBottom: 14,
  },
  entryLink: {
    color: "#082c45",
    display: "flex",
    justifyContent: "center",
    backgroundColor: "white",
    padding: 5,
    borderRadius: 20,
    width: 60,
    marginRight: 30,
  },
  linkContainer: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    alignContent: "space-between",
    marginTop: 10,
  },
  entryText: {
    color: "#082c45",
    textAlign: "center",
    fontSize: 20,
  },
  portfolioColumn: {
    alignItems: "center",
  },
});
